name: 'weather_project'
version: '1.0.0'
config-version: 2
profile: 'stack_profile'

model-paths: ["models"]
macro-paths: ["macros"]

models:
  weather_project:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
